### PR TITLE
typo fix - update readme.md

### LINKED ISSUE #15: typo in README.md file
Operating system: Windows(doesn't matter because its a typo bug)

Steps to reproduce the bug:
To reproduce the typo error, search for the word **instalation** in README.md

### PR DESCRIPTION
**Pull request by Parikshit-Hooda**
Changed **instalation** to **installation**.
Fixes #15

### CODE REVIEW

**Comment by Parikshit-Hooda** [comment]
Writing tests - not required.

**Comment by Parikshit-Hooda** [comment]
@pantuza

**Comment by pantuza** [comment]
Hi @Parikshit-Hooda , I no longer have permissions to merge changes. Wait for some maintainer to evaluate your Pull Request. Thanks for contributing.

**Review by pantuza — APPROVED** [review]
For sure it was a typo. Thanks.

**Comment by dioni21** [comment]
Typo

**Pull request merged**
