### PR TITLE
Fix setup

### PR DESCRIPTION
**Pull request by igorg**
Reorganizes dependencies in setup.py. The current configuration stales pip to version 8.2.1 making it impossible to update it when glogcli is used as a lib.
Makes the tox build green (with some ignoring).
Minor fixes

### CODE REVIEW

**Comment by nolliv** [comment]
Can someone merge this? It's very important both for global installs of glogcli and other cmd line tools depending on it =D

**Comment by victor-mendes-eduardo** [comment]
Hi, @igorg I just have one doubt about the removal of the encode calls on formats.py and input.py.
We have had a few issues especially using python 2.7 when dumping logs to file. 
As soon as this is cleared I'll merge your patch. 
Thanks very much for the contribution and sorry for the delayed response.

**Comment by igorg** [comment]
Hi, @victor-mendes-eduardo.

The way `encode` was being used caused python 3.x tests to fail. I just removed the call and all tests passed for python 2.7 and 3.x so I thought I wasn't creating a regression. But now you mentioned, I may be creating a regression indeed if the tests don't cover this issues.

Can you provide a specific scenario when the log dumping fails? That way I can improve my PR and make sure no regressions will happen.

**Comment by sinvalmendes** [comment]
Hi, @igorg 

I tested the encode("utf-8") issue using Python3.6 and the error that the tests were poiting is due to the return type of the encode function in Python3, it returns a 'bytes' instead of a 'str' (like in Python2). 

That being said, the idea of glog-cli running on Python3 does not work right now, but I think that it can be done in the future, we do not support Python3 because we don't run and develop in Python3, but we can use the lib six to make it happen.

What I would recommend you to do, make another change in your PR to use the six lib to support the Python3 in the code using encode.("utf-8"), it's seems pretty simple to do. By doing this we do not break the feature of dump in Python2. What you must do as well is, in the code that will run for Python3, when the encode function is called it get the array of bytes and turns it into a str and returns it.

Thank you for the support.

**Comment by victor-mendes-eduardo** [comment]
Hi @igorg , just one more issue, could you return the **self.encode_message(message)** on the **formats.py:36** ? Once it's done I'll merge this pull request. Thanks again for the contribution.

**Comment by igorg** [comment]
Done, @victor-mendes-eduardo.

**Pull request merged**
